### ISSUE TITLE
Crash on "Navigation failed because browser has disconnected!"

### ISSUE THREAD

**Issue by jaimeiniesta** [jaimeiniesta/axe-core-lambda-http#1]
When trying to validate [this url](https://www.unthsc.edu/2018-rand-horsman-scholarship-golf-tournament/rand-horsman-sponsorship/), the script crashes with:

```
  Oct 24th 10:53:12am INFO production 3d75ab7 request: id=3d0d58e9-d76a-11e8-9ce2-d1320534c776 ip=81.35.136.69 method=GET path=/ query=url=https%3A%2F%2Fwww.unthsc.edu%2F2018-rand-horsman-scholarship-golf-tournament%2Frand-horsman-sponsorship%2F
  Oct 24th 10:53:14am ERRO production 3d75ab7 Runtime error { error: 'Navigation failed because browser has disconnected!',
  Oct 24th 10:53:14am ERRO production 3d75ab7   stack: 'Error: Navigation failed because browser has disconnected!\n    at Connection.NavigatorWatcher._eventListeners.helper.addEventListener (/var/task/node_modules/puppeteer/lib/FrameManager.js:1146:117)\n    at emitNone (events.js:111:20)\n    at Connection.emit (events.js:208:7)\n    at Connection._onClose (/var/task/node_modules/puppeteer/lib/Connection.js:123:10)\n    at WebSocketTransport._ws.addEventListener.event (/var/task/node_modules/puppeteer/lib/WebSocketTransport.js:45:22)\n    at WebSocket.onClose (/var/task/node_modules/ws/lib/event-target.js:124:16)\n    at emitTwo (events.js:126:13)\n    at WebSocket.emit (events.js:214:7)\n    at WebSocket.emitClose (/var/task/node_modules/ws/lib/websocket.js:172:10)\n    at Socket.socketOnClose (/var/task/node_modules/ws/lib/websocket.js:781:15)\n  -- ASYNC --\n    at Frame.<anonymous> (/var/task/node_modules/puppeteer/lib/helper.js:144:27)\n    at Page.goto (/var/task/node_modules/puppeteer/lib/Page.js:579:49)\n    at Page.<anonymous> (/var/task/node_modules/puppeteer/lib/helper.js:145:23)\n    at analyze (/var/task/app.js:23:16)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }
  Oct 24th 10:53:14am ERRO production 3d75ab7 response: duration=1.457s id=3d0d58e9-d76a-11e8-9ce2-d1320534c776 ip=81.35.136.69 method=GET path=/ query=url=https%3A%2F%2Fwww.unthsc.edu%2F2018-rand-horsman-scholarship-golf-tournament%2Frand-horsman-sponsorship%2F size=656 B status=500
  Oct 24th 10:53:14am INFO REPORT RequestId: 3d0e1bac-d76a-11e8-b024-f5d151a25466	Duration: 1467.81 ms	Billed Duration: 1500 ms 	Memory Size: 2048 MB	Max Memory Used: 296 MB
```

**Comment by jaimeiniesta** [comment]
A similar error on these URLs:

* https://www.wisconsin.edu/offices/
* https://www.wisconsin.edu/for-wisconsin/2018/10/17/uw-madison-offers-todays-middle-school-students-chance-to-study-yesterdays-people-of-aztalan/

```
  Oct 25th 10:23:40am ERRO production 3d75ab7 Runtime error { error: 'Navigation failed because browser has disconnected!',
  Oct 25th 10:23:40am ERRO production 3d75ab7   stack: 'Error: Navigation failed because browser has disconnected!\n    at Connection.NavigatorWatcher._eventListeners.helper.addEventListener (/var/task/node_modules/puppeteer/lib/FrameManager.js:1146:117)\n    at emitNone (events.js:111:20)\n    at Connection.emit (events.js:208:7)\n    at Connection._onClose (/var/task/node_modules/puppeteer/lib/Connection.js:123:10)\n    at WebSocketTransport._ws.addEventListener.event (/var/task/node_modules/puppeteer/lib/WebSocketTransport.js:45:22)\n    at WebSocket.onClose (/var/task/node_modules/ws/lib/event-target.js:124:16)\n    at emitTwo (events.js:126:13)\n    at WebSocket.emit (events.js:214:7)\n    at WebSocket.emitClose (/var/task/node_modules/ws/lib/websocket.js:172:10)\n    at Socket.socketOnClose (/var/task/node_modules/ws/lib/websocket.js:781:15)\n  -- ASYNC --\n    at Frame.<anonymous> (/var/task/node_modules/puppeteer/lib/helper.js:144:27)\n    at Page.goto (/var/task/node_modules/puppeteer/lib/Page.js:579:49)\n    at Page.<anonymous> (/var/task/node_modules/puppeteer/lib/helper.js:145:23)\n    at analyze (/var/task/app.js:23:16)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }
  Oct 25th 10:23:40am ERRO production 3d75ab7 response: duration=1.09s id=469da857-d82f-11e8-b6ac-bd15f15c55a0 ip=81.35.136.69 method=GET path=/ query=url=https%3A%2F%2Fwww.wisconsin.edu%2Foffices%2F size=656 B status=500
  Oct 25th 10:23:40am INFO REPORT RequestId: 469e1e25-d82f-11e8-a162-273e3da0e81e	Duration: 1111.80 ms	Billed Duration: 1200 ms 	Memory Size: 2048 MB	Max Memory Used: 350 MB
```

**Comment by jaimeiniesta** [comment]
Upgraded puppetter from 1.9.0 to 1.11.0 - this keeps failing because browser disconnects, only in AWS lambda.

**Comment by jaimeiniesta** [comment]
Upgraded to puppeteer 1.11.2 - this keeps failing.

**Comment by jaimeiniesta** [comment]
This has now been fixed using axe-puppeteer:

https://github.com/jaimeiniesta/axe-puppeteer-lambda-http
